version: '3.8'

services:
  app:
      build:
        context: ..
        dockerfile: Dockerfile
      container_name: app
      volumes:
      - ../src/:/usr/backend_app/src
      working_dir: /usr/backend_app/
      ports:
        - "8080:8080"
      command:  bash -c 'python src/manage.py runserver 0.0.0.0:8080'
      env_file:
        - ../.env
      networks:
        - app-network



networks:
  app-network:
    driver: bridge
